name: ğŸ“¦ Publish NPM
on: { push: { branches: [master] } }

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: ğŸ§ Checkout
        uses: actions/checkout@v5
        with: { fetch-depth: 0 }

      - name: ğŸŸ¢ Update node
        uses: actions/setup-node@v6
        with: { node-version: 24, registry-url: 'https://registry.npmjs.org' }

      - name: ğŸ¦– Set up Deno
        uses: denoland/setup-deno@v2
        with: { deno-version: v2.x, cache: true }

      - name: ğŸ“¦ Build npm packages
        run: deno run -A npm.ts
